project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Dexterous Data"
  site-url: "https://dexterousdata.com"
  navbar:
    logo: /assets/images/DxDLogo.png
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: "mailto:dexterous.data.llc@gmail.com"
  page-footer:
    center: |
      © 2026 Dexterous Data LLC · All Rights Reserved

format:
  html:
    theme: [flatly, custom.scss]
    email-obfuscation: javascript
