---
title: "Services"
format: html
---

DxD can provide technical insight and custom solutions for your data concerns. With a focus on **clarity, structure, and reproducibility**, solutions remove friction, accelerate onboarding and team alignment, and automate key operations.  

---

## Training

Revamping a tech stack? Leveraging a new technology? 

Cut through the noise, save your team's time, and get just what you need. DxD custom training offers custom websites, documentation, and notebooks highlighting your business needs and offering standardized approaches for consistent results.

---

## Consulting & Process Design

Planning a new project? Need insight into data collection or analysis? Looking for reliabile analysis results so your move forward with your business goals? 

With years of research and analytics experience, DxD has a keen eye turning data into meaning efficiently. From data big and small, whether survey, images, text, or financial records, DxD has built robust, reproducible analysis pipelines. 

---

## Tutoring

Learning a new language or technique? Trying to level up your career? Working on a degree? Want to free up your time with automation? 

One-on-one mentoring is ideal fo helping individuals meet their personal goals. By understanding unique goals and roadblocks, DxD will work with you to get where you want to be.

Sign up for a free 30 minute assessment [here](tutoring.qmd)!

---

## Work With DxD

Interested in training, consulting, or mentoring?

Email me at <dexterous.data.llc@gmail.com> and I’ll review it and respond if it is a good fit.
